---
- name: Docker Login Build Start
  hosts: localhost
  gather_facts: no
  vars:
    docker_id: "{{ lookup('env', 'docker_id') }}"
    docker_key: "{{ lookup('env', 'docker_key') }}"
    container_name: myweb
    image_tag: "{{ lookup('env','BUILD_NUMBER') }}"
    image_name: "{{ docker_id }}/hello_tomcat:{{ image_tag }}"
  tasks:
  - block:
    - name: Login to Docker Hub
      docker_login:
        username: "{{ docker_id }}"
        password: "{{ docker_key }}"
        state: present
    - name: Image Build with WAR
      docker_image:
        build:
          path: .
          rm: yes
        name: "{{ image_name }}"
        push: yes
        source: build
    always:
    - name: Logout to Docker Hub
      docker_login:
        username: "{{ docker_id }}"
        state: absent
