- hosts: localhost
  gather_facts: no

  vars:
    docker_id: "{{ lookup('env', 'docker_id') }}"
    container_name: myweb
    image_tag: "{{ lookup('env', 'BUILD_NUMBER') }}"
    image_name: "{{ docker_id }}/hello_tomcat:{{ image_tag }}"
    

  tasks:
  - name: Deploy Deployments
    k8s:
      state: present
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: myweb
          namespace: default
        spec:
          replicas: 3
          selector:
            matchLabels:
              app: myweb
          template:
            metadata:
              labels:
                app: myweb
            spec:
              containers:
              - name: mycon
                image: "{{ image_name }}"
                ports:
                - containerPort: 8080
  - name: Deploy Service
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: myweb
          namespace: default
        spec:
          type: NodePort
          selector:
            app: myweb
          ports:
          - port: 8080
            targetPort: 8080
            nodePort: 30001
